const IDEA_CODE = {
  IDEA_OK: 100,
  IDEA_NAME_MISSING: 101,
  IDEA_DESC_MISSING: 102,
  IDEA_BUDGET_INVALID: 103,
  IDEA_COMMENT_STATUS_MISSING: 104,
  IDEA_PEOPLE_INVALID: 105
};

export { IDEA_CODE };
